spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devlog?serverTimezone=UTC&characterEncoding=UTF-8
    username: dev_user
    password: devpass123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 개발 중에는 update, 추후엔 validate 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true